# machine:
#   node:
#     version: 6.1.0
# dependencies:
#   pre:
#     # Install Yarn from package manager
#     - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
#     - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
#     - sudo apt-get update -qq
#     - sudo apt-get install -y -qq yarn
#   cache_directories:
#     - "~/.cache/yarn"
#   override:
#       - yarn install
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  test:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: Run tests
          command: yarn run test
    
workflows:
  version: 2
  build:
    jobs:
      - build
      - test:
          requires:
            - build
        